image: node:20-alpine

variables:
  GIT_DEPTH: "1"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  only:
    - main